version: '3.7'

services:

  products-db:
    image: psodpromapps/products-db:m2
    build:
      context: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=wired
    networks:
      - wb-net

  products-api:
    image: psodpromapps/products-api:m2
    build:
      context: products-api
    ports:
      - "8081:80"
    networks:
      - wb-net
    depends_on:
      - products-db

  stock-api:
    image: psodpromapps/stock-api:m2
    build:
      context: stock-api
    ports:
      - "8082:8080"
    networks:
      - wb-net
    depends_on:
      - products-db
  
  web:
    image: psodpromapps/web:m2
    build:
      context: web
    ports:
      - "8080:80"
    networks:
      - wb-net
    depends_on:
      - products-api      
      - stock-api

networks:
  wb-net: