global:
  scrape_interval: 10s

scrape_configs:

  - job_name: "pushgateway"
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
      
  - job_name: "web"
    metrics_path: /metrics
    static_configs:
      - targets: ["web"]

  - job_name: "products-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["products-api"]

  - job_name: "stock-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["stock-api:8080"]
