global:
  scrape_interval: 10s

scrape_configs:

  - job_name: "pushgateway"
    metrics_path: /metrics
    # you should always set honor_labels for pushgateway:
    # honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
