{
 "title": "ps-prom-apps",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Web App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(job, method, instance) (http_requests_in_progress{job=\"wb-web_web\"})"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, method, instance) (http_requests_in_progress{job=\"wb-web_web\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "90th Percentile Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without(code, job, method, instance) (rate(http_request_duration_seconds_bucket{job=\"wb-web_web\", code=\"200\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_total_memory_bytes{job=\"wb-web_web\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "app_info{job=\"wb-web_web\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"wb-web_web\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "Stock API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(job, instance) (http_requests_in_progress{job=\"wb-web_stock-api\"})"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, instance) (http_requests_in_progress{job=\"wb-web_stock-api\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "90th Percentile Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum without(job, instance) (rate(http_request_duration_seconds_bucket{job=\"wb-web_stock-api\"}[5m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(go_memstats_alloc_bytes{job=\"wb-web_stock-api\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 10 },
   "targets": [
    {
     "expr": "app_info{job=\"wb-web_stock-api\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"wb-web_stock-api\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "Products API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Current Active Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(job, instance,method, status, outcome, uri, exception) (rate(http_server_requests_seconds_count{job=\"wb-web_products-api\"}[5m]))"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(job, instance,method, status, outcome, uri, exception) (rate(http_server_requests_seconds_count{job=\"wb-web_products-api\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 19 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum without(job, instance,method, status, outcome, exception) (rate(http_server_requests_seconds_sum{job=\"wb-web_products-api\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"wb-web_products-api\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Products",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 19, "y": 19 },
   "targets": [
    {
     "expr": "app_info{job=\"wb-web_products-api\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_usage{job=\"wb-web_products-api\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "Pricing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Last Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "batch_duration_seconds", "legendFormat": "minutes" }
   ]
  },
  {
   "title": "Last Success",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "batch_last_success_seconds*1000",
     "legendFormat": "minutes"
    }
   ]
  },
  {
   "title": "Last Error",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "batch_last_error_seconds*1000", "legendFormat": "minutes" }
   ]
  },
  {
   "title": "Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 28 },
   "targets": [
    {
     "expr": "app_info{job=\"batch\"}"
    }
   ]
  }
 ]
}