version: '3.7'

services:

  fortio-web:
    image: fortio/fortio:1.6.8
    command: load -c 32 -qps 25 -t 60s http://web
    networks:
      - wb-net

  fortio-stock:
    image: fortio/fortio:1.6.8
    command: load -c 10 -qps 5 -t 30s http://stock-api:8080/stock/1
    networks:
      - wb-net

  fortio-products:
    image: fortio/fortio:1.6.8
    command: load -c 8 -qps 50 -t 45s http://products-api/products
    networks:
      - wb-net

networks:
  wb-net:
    external: true
    name: wiredbrain